function calibrate_limits_and_home()
% calibrate_limits_and_home
% Manual calibration:
%  - torque OFF
%  - for each motor: move to MIN extreme (ENTER), then MAX extreme (ENTER)
%  - coupled pair (2,3) calibrated together
%  - then move whole arm to HOME pose and press ENTER to record HOME
%
% Outputs:
%   MATLAB/calibration/servo_cal_user.mat
%   MATLAB/calibration/servo_cal_user.m

clc;

% ---------- SETTINGS ----------
port = "COM18";
baud = 1000000;

ids = [1 2 3 4 5 6];

% Motors 2 & 3 are coupled and must move together
coupledPair = [2 3];

% Servo type by ID order above (true=AX 0..1023, false=MX 0..4095)
isAX = [false false false true true true];

% MoveIt joint order [base shoulder elbow wrist ee] maps to servo IDs:
moveitToServoID = [1 2 4 5 6];

% Direction signs for MoveIt joints (keep your current defaults for now)
dirSignMoveIt = [-1 +1 +1 -1 +1];

% ---------- CONNECT ----------
addpath(genpath(fullfile(pwd,"scripts")));
hw = robot_hw_rb150_raw6motor(port, baud);

fprintf("Torque OFF so you can move by hand...\n");
hw.torqueOff();
pause(0.25);

fprintf("\nWe will record RAW min/max for each motor.\n");
fprintf("For each prompt: move to the EXTREME, then press ENTER.\n");
fprintf("Try NOT to cross the wrap-around boundary (0) if possible.\n\n");

rawMin = nan(6,1);
rawMax = nan(6,1);

% ---------- CALIBRATE ID1 ----------
calibrate_single(1);

% ---------- CALIBRATE COUPLED PAIR (2,3) ----------
fprintf("\n=== Coupled Pair Calibration: IDs 2 & 3 ===\n");
fprintf("IMPORTANT: Move the coupled shoulder mechanism as a unit.\n\n");

input("Move coupled pair to MIN extreme, then press ENTER...", "s");
r2a = readRaw(2); r3a = readRaw(3);
fprintf("Captured MIN: ID2=%d, ID3=%d\n", round(r2a), round(r3a));

input("Move coupled pair to MAX extreme, then press ENTER...", "s");
r2b = readRaw(2); r3b = readRaw(3);
fprintf("Captured MAX: ID2=%d, ID3=%d\n", round(r2b), round(r3b));

[rawMin(idIndex(2)), rawMax(idIndex(2))] = orderRange(r2a, r2b);
[rawMin(idIndex(3)), rawMax(idIndex(3))] = orderRange(r3a, r3b);

% ---------- CALIBRATE ID4, ID5, ID6 ----------
calibrate_single(4);
calibrate_single(5);
calibrate_single(6);

% ---------- CAPTURE HOME ----------
fprintf("\n========================================\n");
fprintf("Now manually move the robot to TRUE HOME pose (vertical up).\n");
fprintf("Press ENTER to record HOME raw positions for all 6 motors.\n");
fprintf("========================================\n");
input("Move to HOME pose and press ENTER...", "s");
rawHome = double(hw.readMotors());

fprintf("HOME raw:\n");
for i = 1:6
    fprintf("  ID%d: %d\n", ids(i), round(rawHome(i)));
end

% ---------- SAVE CALIBRATION ----------
cal = struct();
cal.createdAt = datestr(now);
cal.port = char(port);
cal.baud = baud;

cal.servoIDs = ids(:);
cal.isAX12   = isAX(:);

cal.rawMin  = rawMin(:);
cal.rawMax  = rawMax(:);
cal.rawHome = rawHome(:);

cal.moveitToServoID = moveitToServoID(:);
cal.dirSignMoveIt   = dirSignMoveIt(:);

cal.coupledPair = coupledPair(:);

% warn if home outside recorded ranges
for i = 1:6
    if cal.rawHome(i) < cal.rawMin(i) || cal.rawHome(i) > cal.rawMax(i)
        warning("HOME for ID%d (%d) is outside recorded range [%d,%d].", ...
            ids(i), round(cal.rawHome(i)), round(cal.rawMin(i)), round(cal.rawMax(i)));
    end
end

calDir = fullfile(pwd, "calibration");
if ~exist(calDir, "dir"), mkdir(calDir); end

matPath = fullfile(calDir, "servo_cal_user.mat");
save(matPath, "cal");

mPath = fullfile(calDir, "servo_cal_user.m");
write_cal_function(mPath, cal);

fprintf("\nSaved calibration:\n  %s\n  %s\n", matPath, mPath);
fprintf("\n(Leave torque OFF for now. You can torque on later in the main demo.)\n");

% ---------- nested helpers ----------
    function idx = idIndex(id)
        idx = find(ids == id, 1);
        if isempty(idx), error("ID%d not in ids list.", id); end
    end

    function r = readRaw(id)
        raw6 = double(hw.readMotors());
        r = raw6(idIndex(id));
    end

    function calibrate_single(id)
        fprintf("\n=== Calibrating ID%d ===\n", id);

        input(sprintf("Move ID%d to MIN extreme, then press ENTER...", id), "s");
        rA = readRaw(id);
        fprintf("Captured MIN raw: ID%d=%d\n", id, round(rA));

        input(sprintf("Move ID%d to MAX extreme, then press ENTER...", id), "s");
        rB = readRaw(id);
        fprintf("Captured MAX raw: ID%d=%d\n", id, round(rB));

        [mn,mx] = orderRange(rA, rB);
        rawMin(idIndex(id)) = mn;
        rawMax(idIndex(id)) = mx;
    end
end

% ---------- local file helpers ----------
function [mn,mx] = orderRange(a,b)
mn = min(a,b);
mx = max(a,b);
end

function write_cal_function(path, cal)
fid = fopen(path, "w");
fprintf(fid, "function cal = servo_cal_user()\n");
fprintf(fid, "%% Auto-generated by calibrate_limits_and_home.m on %s\n\n", cal.createdAt);

fprintf(fid, "cal.createdAt = '%s';\n", cal.createdAt);
fprintf(fid, "cal.port = '%s';\n", cal.port);
fprintf(fid, "cal.baud = %d;\n", cal.baud);

fprintf(fid, "cal.servoIDs = [%s]'';\n", numlist(cal.servoIDs));
fprintf(fid, "cal.isAX12   = [%s]'';\n", numlist(double(cal.isAX12)));

fprintf(fid, "cal.rawMin  = [%s]'';\n", numlist(cal.rawMin));
fprintf(fid, "cal.rawMax  = [%s]'';\n", numlist(cal.rawMax));
fprintf(fid, "cal.rawHome = [%s]'';\n", numlist(cal.rawHome));

fprintf(fid, "cal.moveitToServoID = [%s]'';\n", numlist(cal.moveitToServoID));
fprintf(fid, "cal.dirSignMoveIt   = [%s]'';\n", numlist(cal.dirSignMoveIt));

fprintf(fid, "cal.coupledPair = [%s]'';\n", numlist(cal.coupledPair));
fprintf(fid, "end\n");
fclose(fid);
end

function s = numlist(v)
v = double(v(:))';
s = sprintf("%.0f ", v);
s = strtrim(s);
end
