function cal = servo_cal_user()
% Auto-generated by calibrate_limits_and_home.m on 22-Feb-2026 02:11:38

cal.createdAt = '22-Feb-2026 02:11:38';
cal.port = 'COM18';
cal.baud = 1000000;
cal.servoIDs = [1 2 3 4 5 6]'';
cal.isAX12   = [0 0 0 1 1 1]'';
cal.rawMin  = [111 1305 1695 196 186 198]'';
cal.rawMax  = [689 2597 2985 802 833 639]'';
cal.rawHome = [180 2157 2134 514 504 220]'';
cal.moveitToServoID = [1 2 4 5 6]'';
cal.dirSignMoveIt   = [-1 1 1 -1 1]'';
cal.coupledPair = [2 3]'';
end
