function test_motor_registers()
clc;

hw = robot_hw_rb150_calibrated_6motor("COM13", 1000000);

hw.torqueOn();
pause(0.3);

regs = hw.readMotorRegisters();

fprintf('\n');
fprintf('ID  TE  CW    CCW   SPD   MOV  TLIM  TCME  MTORQ  ALED  SHDN  VOLT  TEMP\n');
fprintf('----------------------------------------------------------------------------\n');
for k = 1:numel(regs)
    fprintf('%2d  %2d  %4d  %4d  %4d   %2d   %4d   %3d   %4d   %3d   %3d   %4d   %4d\n', ...
        regs(k).id, ...
        regs(k).torque_enable, ...
        regs(k).cw_angle_limit, ...
        regs(k).ccw_angle_limit, ...
        regs(k).moving_speed, ...
        regs(k).moving, ...
        regs(k).torque_limit, ...
        regs(k).torque_ctrl_mode_enable, ...
        regs(k).max_torque, ...
        regs(k).alarm_led, ...
        regs(k).shutdown, ...
        regs(k).present_voltage, ...
        regs(k).present_temperature);
end
end